# Generated by Django 5.0.2 on 2024-03-01 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('price', models.FloatField()),
                ('desc', models.TextField()),
                ('category', models.CharField(max_length=200)),
                ('image', models.TextField()),
                ('rating', models.FloatField()),
                ('rating_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cart_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('products_in_cart', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom_app.user_model')),
            ],
        ),
    ]
