# Generated by Django 5.0.2 on 2024-03-02 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0002_product_model_cart_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_model',
            name='products_in_cart',
        ),
        migrations.AddField(
            model_name='cart_model',
            name='products_in_cart',
            field=models.ManyToManyField(to='ecom_app.product_model'),
        ),
    ]
