# Generated by Django 5.0.2 on 2024-03-06 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0003_remove_cart_model_products_in_cart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_model',
            name='products_in_cart',
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ecom_app.cart_model')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom_app.product_model')),
            ],
        ),
    ]
