# Generated by Django 5.0.2 on 2024-03-07 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0005_cart_model_products_in_cart_delete_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_model',
            name='products_in_cart',
        ),
        migrations.AlterField(
            model_name='cart_model',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom_app.user_model'),
        ),
        migrations.CreateModel(
            name='Cart_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom_app.product_model')),
            ],
        ),
        migrations.AddField(
            model_name='cart_model',
            name='items',
            field=models.ManyToManyField(to='ecom_app.cart_item'),
        ),
    ]
