# Generated by Django 5.0.2 on 2024-03-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0007_alter_cart_item_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_model',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product_model',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='product_model',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='product_model',
            name='rating_count',
        ),
        migrations.AddField(
            model_name='product_model',
            name='author',
            field=models.CharField(default='amit pandey', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_model',
            name='subtitle',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_model',
            name='url',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
